<Project>
    <PropertyGroup>
        <VersionPrefix>0.3.0</VersionPrefix>
        <VersionSuffix>beta.2</VersionSuffix>

        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <Authors>WithLithum</Authors>
        <Company>WithLithum</Company>
        <ProductName>$(SolutionName)</ProductName>
        <Copyright>Copyright (C) 2025-2026 WithLithum.</Copyright>
        <RepositoryUrl>https://github.com/WithLithum/native-wrapper-gen.git</RepositoryUrl>
        <PackageProjectUrl>https://github.com/WithLithum/native-wrapper-gen</PackageProjectUrl>
    </PropertyGroup>
</Project>
