<Project>
  <PropertyGroup>
    <VersionPrefix>0.1.2</VersionPrefix>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Authors>WithLithum</Authors>
    <Company>WithLithum</Company>
    <ProductName>$(SolutionName)</ProductName>
    <RepositoryUrl>https://github.com/WithLithum/native-wrapper-gen.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/WithLithum/native-wrapper-gen</PackageProjectUrl>
  </PropertyGroup>
</Project>