name: Generator bug report
description: Report a problem with the generator tool.
title: "[Bug]: "
labels: ["type/bug", "new"]
body:
  - type: markdown
    attributes:
      value: |
          Thank you for taking your time to report a problem. Please fill the form below appropriately to enable us to triage and address the problem in a timely fashion.

          Before you continue, read the [CONTRIBUTING guide](https://github.com/WithLithum/native-wrapper-gen/blob/trunk/CONTRIBUTING.md).
  - type: textarea
    attributes:
        label: Describe the problem
        description: |
            A summary of what is the problem you are trying to report.
    validations:
        required: true
  - type: dropdown
    attributes:
        label: Affected generator
        description: Which generator / script hook that you used when you encountered the problem? Select all the affected, if possible.
        multiple: true
        options:
          - Script Hook V .NET (SHVDN)
          - RAGE Plugin Hook (RPH)
          - Others / I don't know
          - Not associated with a generator
    validations:
        required: true
  - type: textarea
    attributes:
        label: Steps to reproduce
        description: |
            Detailed instructions on how to reproduce the issue. The better you describe how to reproduce, the sooner the problem can be worked on.
    validations:
        required: true
  - type: textarea
    attributes:
        label: Expected behaviour
        description: |
            Describe what should have happened instead?
  - type: textarea
    attributes:
        label: Console output
        description: What did the program output to the console? This is automatically put into a code block (backticks not needed)
        render: shell
  - type: textarea
    attributes:
        label: Sample code
        description: If applicable, what was the errored code generated by the generator?
        render: C#
  - type: textarea
    attributes:
        label: Extra information
        description: If applicable, put additional information here.
