// SDPX-FileCopyrightText: 2025-2026 WithLithum
// SPDX-License-Identifier: Apache-2.0

using WithLithum.NativeWrapperGen.Models;

namespace WithLithum.NativeWrapperGen.Generation;

partial class WrapperFileGenerator
{
    private readonly IShimGenerator _shimGenerator;
    private readonly GeneratorSettings _settings;

    public WrapperFileGenerator(GeneratorSettings settings, IShimGenerator shimGenerator)
    {
        _settings = settings;
        _shimGenerator = shimGenerator;
    }

    private string GetStringForType(ScriptCommandReturnType returnType)
    {
        return _settings.TypeSettings.GetTypeName(returnType);
    }

    private WrapperEmitContext CreateContext(string hash,
        string nameSpace,
        ScriptCommandInfo commandInfo)
    {
        return new WrapperEmitContext
        {
            Hash = hash,
            SymbolNameHash = MethodNameConverter.HashToMethodName(hash),
            CommandInfo = commandInfo,
            Namespace = nameSpace,
            ReturnTypeString = GetStringForType(commandInfo.ReturnType)
        };
    }

    public void WritePartial(string nameSpace,
        string className,
        in WrapperSectionContext context,
        TextWriter writer)
    {
        writer.WriteLine("// <auto-generated />");

        WriteNameSpaceScopeHeader(nameSpace, writer);
        WriteClassScopeHeader(className, writer);

        foreach (var command in context.Commands)
        {
            _shimGenerator.WriteMethod(
                CreateContext(
                    command.Key,
                    context.Namespace,
                    command.Value),
                writer);
        }

        WriteScopeFooter(writer); // end class
        WriteScopeFooter(writer); // end namespace
    }
}
