namespace WithLithum.NativeWrapperGen.Generation;

using WithLithum.NativeWrapperGen.Models;

partial class WrapperFileGenerator
{
    private readonly GeneratorSettings _settings;
    private readonly TextWriter _writer;

    public WrapperFileGenerator(TextWriter writer,
        GeneratorSettings settings)
    {
        _writer = writer;
        _settings = settings;
    }

    internal WrapperEmitContext CreateContext(string hash, ScriptCommandInfo commandInfo)
    {
        return new WrapperEmitContext
        {
            Hash = hash,
            SymbolNameHash = MethodNameConverter.HashToMethodName(hash),
            CommandInfo = commandInfo,
            ReturnTypeString = GetStringForType(commandInfo.ReturnType)
        };
    }

    public void WritePartial(string nameSpace,
        string className,
        IReadOnlyDictionary<string, ScriptCommandInfo> partial)
    {
        _writer.WriteLine("/// <auto-generated />");

        WriteNameSpaceScopeHeader(nameSpace);
        WriteClassScopeHeader(className);

        foreach (var command in partial)
        {
            WriteWrapperMethod(CreateContext(command.Key, command.Value));
        }

        WriteScopeFooter(); // end class
        WriteScopeFooter(); // end namespace
    }
}