name: Create wrappers

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: Setup .NET
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        global-json-file: global.json
    - name: Restore dependencies (root)
      run: dotnet restore
    - name: Generate wrappers
      run: pwsh "${{ github.workspace }}/GenerateNativeWrapper.ps1"
    - name: Submit NuGet packages
      run: dotnet nuget push "${{ github.workspace }}/bin/*.nupkg" --skip-duplicate --source "https://nuget.pkg.github.com/WithLithum/index.json" --api-key ${{ github.token }}
    - name: Publish artefact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # 7.0.1
      with:
        name: For_player.zip
        path: ${{ github.workspace }}/bin/NativeWrapper.zip
        if-no-files-found: warn
        archive: false

        